#!/bin/sh

# Exit on error
set -e

DOTFILES="
.gitconfig
.githelpers
.gitignore_global
.oh-my-zsh
.tmux.conf
.vim
.vimrc
.zshrc
"

OH_MY_ZSH_PLUGINS="
git://github.com/zsh-users/zsh-syntax-highlighting.git
"

OH_MY_ZSH_THEMES="
https://gist.githubusercontent.com/jcomo/82fde75040185592bbc8a520a7f78b7e/raw/c7689987118924e8b6025f12cf004c0a82fa0426/jcomo.zsh-theme
"

success () {
    echo "\033[32m[OK]   \033[0m $1"
}

warn () {
    echo "\033[33m[WARN] \033[0m $1"
}

info () {
    echo "\033[36m[INFO] \033[0m $1"
}

silence () {
    if [[ $DEBUG = 1 ]]; then
        "$@"
    else
        "$@" &>/dev/null
    fi
}

confirm () {
    message="$1"
    read -p "$1 Continue? [yN] " response

    if [[ "y" != $response ]]; then
        info "Exiting..."
        exit 1
    fi
}

link_dotfiles () {
    for dotfile in $DOTFILES; do
        silence ln -sf "$HOME/dotfiles/$dotfile" "$HOME" || warn "Failed to link $dotfile" && \
            info "Linked $dotfile"
    done
}

install_oh_my_zsh () {
    cd $HOME/dotfiles
    git clone git@github.com:robbyrussell/oh-my-zsh .oh-my-zsh
}

install_zsh_plugins () {
    mkdir -p $HOME/.oh-my-zsh/custom/plugins
    cd $HOME/.oh-my-zsh/custom/plugins

    for plugin in $OH_MY_ZSH_PLUGINS; do
        silence git clone $plugin || \
            warn "Failed to install plugin at $plugin - it may already be installed"
    done
}

install_zsh_themes () {
    mkdir -p $HOME/.oh-my-zsh/custom/themes
    cd $HOME/.oh-my-zsh/custom/themes

    for theme in $OH_MY_ZSH_THEMES; do
        silence curl -sO $theme || \
            warn "Failed to install theme $theme"
    done
}

prompt_for_git_config () {
    option=$1
    prompt="$2"

    if [[ ! `git config --global $option` ]]; then
        read -p "$prompt: " item
        git config --global $option "$item"
    fi
}

configure_git () {
    prompt_for_git_config user.name "Enter your name"
    prompt_for_git_config user.email "Enter your email"

    git config --global core.excludesfile "$HOME/.gitignore_global"
}


main () {
    confirm "Running this installation will wipe all previous dotfiles."
    info "Installing oh-my-zsh"; install_oh_my_zsh
    info "Installing zsh plugins"; install_zsh_plugins
    info "Installing zsh themes"; install_zsh_themes
    info "Linking dotfiles"; link_dotfiles
    info "Configuring git"; configure_git
    success "Dotfiles installed!"
    success "Run 'source ~/.zshrc' to get going"
}


if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
    if [[ "debug" = $1 ]]; then
        DEBUG=1
    else
        DEBUG=0
    fi

    main "$@"
fi
